apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: sudeepj24/wisecowimg:latest
        ports:
        - containerPort: 4499
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        configMap:
          name: wisecow-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wisecow-config
data:
  wisecow.sh: |
    #!/bin/bash
    while true; do
      echo "$(fortune | cowsay)"
      sleep 5
    done
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
  type: LoadBalancer
